config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users

  root 'clinics#index'
  
  resources :clinics do
    resources :appointments
    resources :doctors
    resources :patientrecords
  end

  resources :patients do
    resources :patientrecords
  end

  

end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
	belongs_to :clinic

	validates :first_name, :middle_name, :last_name, :contact_number, presence: true
	validates :contact_number, length: {is: 11, message: "should have 11 digits"}
end

app/models/clinic.rb
class Clinic < ActiveRecord::Base

	belongs_to :user
	has_many :doctors
	has_many :appointments
	has_many :patientrecords
	has_many :patients, through: :patientrecords

	
	validates :clinic_name, :address, :city, :province, :telephone_number, :mobile_number, :description, presence: true
	validates :telephone_number, length: {is: 7, message: "should have 7 digits"}
	validates :mobile_number, length: {is: 11, message: "should have 11 digits"}
	validates :description, length:{maximum: 500}
end

app/models/doctor.rb
class Doctor < ActiveRecord::Base
	belongs_to :clinic

	validates :first_name, :middle_name, :last_name, :birthdate, :prc_number, :contact_num, presence: true
	validates :contact_num, length: {is: 11, message: "should have 11 digits"}
end

app/models/patient.rb
class Patient < ActiveRecord::Base
	has_many :patientrecords
	has_many :clinics , through: :patientrecords
	validates 	:first_name, 
				:middle_name, 
				:last_name, 
				:birthdate, 
				:home_address, 
				:home_city, 
				:home_province,
				:marital_status,
				:occupation,
				presence: true
  	validates :gender, presence: true
	validates :contact_number, length: {is: 11, message: "should have 11 digits"}
end

app/models/patientrecord.rb
class Patientrecord < ActiveRecord::Base
	belongs_to :patient
	belongs_to :clinic
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :clinic
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!

  
  def get_clinic
		@user = User.find(current_user.id)
		@clinic = @user.clinic
	end
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
	before_action :get_clinic

	def index

		@appointments = Appointment.where("clinic_id == ?", @clinic.id)

	end

	def new
		@appointment = Appointment.new
	end

	def edit
		@appointment = @clinic.appointments.find(params[:id])
	end

	def show

		begin
			@appointment = @clinic.appointments.find(params[:id])
		
			@patient = Patient.where("first_name = ? AND last_name = ?", @appointment.first_name, @appointment.last_name).first
			

			unless @patient
				@patient = Patient.new
				@patient.first_name = @appointment.first_name
				@patient.last_name = @appointment.last_name
				@patient.middle_name = @appointment.middle_name
				@patient.contact_number = @appointment.contact_number
			end

			@patientRecord = @patient.patientrecords.new
			@patientRecord.datetime_schedule = @appointment.preferred_date

			rescue ActiveRecord::RecordNotFound
				redirect_to clinics_path, :flash => { :alert => "No Record Found" } 
		end
		

	end

	def update
		@appointment = @clinic.appointments.find(params[:id])

		if @appointment.update(appointment_params) 
			redirect_to clinics_path
		else
			render 'edit'
		end

	end
	
	def create
		@appointment = Appointment.new(appointment_params)
		@appointment.clinic_id = @clinic.id

		if @appointment.save
			redirect_to clinics_path
		else
			render 'new'
		end

	end

	private

	def get_clinic
		@user = User.find(current_user.id)
		@clinic = @user.clinic
	end

	def appointment_params
		params.require(:appointment).permit(:first_name, :middle_name, :last_name, :contact_number, :preferred_date)
	end
end

app/controllers/clinics_controller.rb
class ClinicsController < ApplicationController
	

  def index
    @user = User.find(current_user.id)
    @clinic = @user.clinic
    
  	if @clinic == nil
  		redirect_to new_clinic_path
  	end

    @appointments = Appointment.where("clinic_id == ? AND preferred_date >= ?",  @clinic, Time.zone.now.beginning_of_day).order(:preferred_date => :asc)
  	
  end

  def new
  	checkClinicExist

  	@clinic = Clinic.new
  end

  def create
  	checkClinicExist
  	@clinic = Clinic.new(clinic_params)
  	@clinic.user_id = current_user.id
  	if @clinic.save
  		redirect_to clinics_path
  	else
  		render 'new'
  	end
  end

  private
  	def clinic_params
		params.require(:clinic).permit(:clinic_name, :address, :city, :province, :telephone_number, :mobile_number, :description)
	end


	def checkClinicExist
		user = User.find(current_user.id)
	  	if user.clinic == nil
	  		return false
	  	else
	  		redirect_to clinics_path
		end
	end
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
	before_action :get_clinic

	def index
		
		@doctors = Doctor.where("clinic_id == ?", @clinic.id)
	end

	def new
		user = User.find(current_user.id)
		@clinic = user.clinic
		@doctor = Doctor.new
	end

	def create
		user = User.find(current_user.id)
		@clinic = user.clinic
		@doctor = Doctor.new(doctor_params)
		@doctor.clinic_id = @clinic.id

		if @doctor.save
			redirect_to clinic_doctors_path
		else
			render 'new'
		end
	end

	def edit
		@doctor = @clinic.doctors.find(params[:id])
	end

	def update
		@doctor = @clinic.doctors.find(params[:id])

		if @doctor.update(doctor_params)
			redirect_to clinic_doctors_path
		else
			render 'edit'
		end

	end

	private

	def get_clinic
		@user = User.find(current_user.id)
		@clinic = @user.clinic
	end
	
	def doctor_params
		params.require(:doctor).permit(:first_name, :middle_name, :last_name, :birthdate, :prc_number, :contact_num);
	end
end

app/controllers/patientrecords_controller.rb
class PatientrecordsController < ApplicationController
	before_action :get_clinic
	def create
		@appointment = @clinic.appointments.find(params[:appointment_id])
		
		@patient = Patient.where("first_name = ? AND last_name = ?", @appointment.first_name, @appointment.last_name).first
		@patientRecord = @patient.patientrecords.new(record_params)
		@patientRecord.clinic_id = @clinic.id

		if @patientRecord.save
			redirect_to clinics_path
		else
			render 'appointments/show'
		end
	end

	def edit
		
	end

	def update

	end

	private

	def record_params
		params.require(:patientrecord).permit(
				:datetime_schedule,
				:occlusion,
				:periodontal_condition,
				:oral_hygiene,
				:denture_location,
				:denture_since,
				:abnormalities,
				:general_condition,
				:nature_of_treatment,
				:allergies,
				:bleeding_history,
				:chronic_ailments,
				:blood_pressure,
				:drug_taken
				)
	end

	def get_clinic
		@user = User.find(current_user.id)
		@clinic = @user.clinic
	end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController

	before_action :get_clinic

	def index
		begin
			@records = Patientrecord.where("clinic_id = ?", @clinic.id)

		rescue ActiveRecord::RecordNotFound
			redirect_to clinics_path 		
		end
	end

	def create
		@appointment = Appointment.find(params[:appointment_id])
		@patient = Patient.new(patient_params)

		if @patient.save
			redirect_to clinics_path
		else
			render 	:template => 'appointments/show'
		end


	end


	private

	def patient_params
		params.require(:patient).permit(:first_name, :middle_name, :last_name, :birthdate, :gender, :home_address, :home_city, :home_province , :contact_number, :marital_status, :occupation);
	end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/clinics_helper.rb
module ClinicsHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/views/appointments/edit.html.erb
<div class="row">
	<div class="col-md-4">
		
	</div>
	<div class="col-md-8">
		<div class="mainbody-container">
			<h1>Set Appointment</h1>

			<%= form_for( @appointment,:url => {:action => 'update', :id => @appointment}) do |f| %>
				<%= render "shared/error_message", :target => @appointment %>
				<div class="form-group">
					<%= f.label :first_name, "First Name" %>
					<%= f.text_field :first_name, autofocus: true, class: 'form-control' %>
				</div>
				<div class="form-group">
					<%= f.label :middle_name, "Middle Name" %>
					<%= f.text_field :middle_name, autofocus: true, class: 'form-control' %>
				</div>
				<div class="form-group">
					<%= f.label :last_name, "Last Name" %>
					<%= f.text_field :last_name, autofocus: true, class: 'form-control' %>
				</div>
				
				<div class="form-group">
					<%= f.label :preferred_date, "Select Date" %>
					<%= f.datetime_select :preferred_date, min: Date.today,:minute_step => 60 ,:ampm => true, :order => [:month, :day, :year], :start_year => Time.now.year, autofocus: true, class: 'form-control' %>
				</div>
				<div class="form-group">
					<%= f.label :contact_number, "Mobile #" %>
					<%= f.text_field :contact_number, autofocus: true, class: 'form-control' %>
				</div>
				<div class="actions">
					<%= f.submit "Submit", class: "btn btn-primary btn-block" %>
				</div>

			<% end %>
		</div>
	</div>
	
</div>

app/views/appointments/new.html.erb
<div class="row">
	<div class="col-md-4">
		
	</div>
	<div class="col-md-8">
		<div class="mainbody-container">
			<h1>Set Appointment</h1>

			<%= form_for(@appointment, {:url => clinic_appointments_path(current_user.id)}) do |f| %>
				<%= render "shared/error_message", :target => @appointment %>
				<div class="form-group">
					<%= f.label :first_name, "First Name" %>
					<%= f.text_field :first_name, autofocus: true, class: 'form-control' %>
				</div>
				<div class="form-group">
					<%= f.label :middle_name, "Middle Name" %>
					<%= f.text_field :middle_name, autofocus: true, class: 'form-control' %>
				</div>
				<div class="form-group">
					<%= f.label :last_name, "Last Name" %>
					<%= f.text_field :last_name, autofocus: true, class: 'form-control' %>
				</div>
				
				<div class="form-group">
					<%= f.label :preferred_date, "Select Date" %>
					<%= f.datetime_select :preferred_date, min: Date.today,:minute_step => 60 ,:ampm => true, :order => [:month, :day, :year], :start_year => Time.now.year, autofocus: true, class: 'form-control' %>
				</div>
				<div class="form-group">
					<%= f.label :contact_number, "Mobile #" %>
					<%= f.text_field :contact_number, autofocus: true, class: 'form-control' %>
				</div>
				
				<div class="actions">
					<%= f.submit "Submit", class: "btn btn-primary btn-block" %>
				</div>

			<% end %>
		</div>
	</div>
	
</div>

app/views/appointments/show.html.erb
<div class="row">
  <div class="col-md-12">
    <h2>Appointee Details</h2>
    <p><span>First Name: </span><%= @appointment.first_name + " " + @appointment.middle_name + " " + @appointment.last_name %></p>
    <p><span>Time of Appointment: </span><%= Date.parse(@appointment.preferred_date.to_s).strftime("%B %e, %Y") + " " + DateTime.parse(@appointment.preferred_date.to_s).strftime("%l:%M %p") %></p> 
  </div>
  <div class="col-md-6">
     
    <div class="row">
      <div class="col-md-12">
          <h3>Add New Patient</h3>

          <%= form_for @patient  do |f| %>
            <%= render "shared/error_message", :target => @patient %>
            <%= hidden_field_tag 'appointment_id', @appointment.id %>
            <div class="col-md-6 form-group">
              <%= f.label :first_name, "First Name" %>
              <%= f.text_field :first_name, autofocus: true, class: 'form-control' %>
            </div>
            <div class="col-md-6 form-group">
              <%= f.label :middle_name, "Middle Name" %>
              <%= f.text_field :middle_name, autofocus: true, class: 'form-control' %>
            </div>
            <div class="col-md-6 form-group">
              <%= f.label :last_name, "Last Name" %>
              <%= f.text_field :last_name, autofocus: true, class: 'form-control' %>
            </div>
            <div class="col-md-6 form-group">
              <%= f.label :occupation, "Occupation" %>
              <%= f.text_field :occupation, autofocus: true, class: 'form-control' %>
            </div>
             <div class="col-md-12 form-group">
              <%= f.label :home_address, "Home Address" %>
              <%= f.text_field :home_address, autofocus: true, class: 'form-control' %>
            </div>
            <div class="col-md-6 form-group">
              <%= f.label :home_city, "City" %>
              <%= f.text_field :home_city, autofocus: true, class: 'form-control' %>
            </div>
            <div class="col-md-6 form-group">
              <%= f.label :home_province, "Province" %>
              <%= f.text_field :home_province, autofocus: true, class: 'form-control' %>
            </div>
            <div class="col-md-6 form-group">
              <%= f.label :contact_number, "Mobile Number" %>
              <%= f.text_field :contact_number, autofocus: true, class: 'form-control' %>
            </div>
            <div class="col-md-6 form-group">
              <%= f.label :birthdate, "Date of Birth" %>
              <%= f.date_field :birthdate, autofocus: true, class: 'form-control' %>
            </div>
            <div class="col-md-6 form-group">
              <%= f.label :gender, "Gender" %>
              <%= f.select :gender,['Male', 'Female']%>
              <%= %>
            </div>
            <div class="col-md-6 form-group">
              <%= f.label :marital_status, "Marital Status" %>
              <%= f.select :marital_status, ['Single', 'Married', 'Widow'] %>
            </div>  
            

            <div class="actions col-md-6">
              <%= f.submit "Add Patient", class: "btn btn-primary btn-block" %>
            </div>
          <% end %>
      </div>
    </div>
  </div>
  <div class="col-md-6">
    <div class="row">
      <div class="col-md-12">
            <h3>Patient's Examination Record Chart</h3>
            <%= form_for @patientRecord, {:url => clinic_patientrecords_path(@clinic)}  do |f| %>
              <%= render "shared/error_message", :target => @patientRecord %>
              <%= hidden_field_tag 'appointment_id', @appointment.id %>
              <div class="col-xs-12 col-sm-6 col-md-6 form-group">
                <%= f.label :datetime_schedule, "Date Schedule" %>
                <%= f.date_field :datetime_schedule, autofocus: true, class: 'form-control' %>
              </div>

              <div class="col-xs-12 col-sm-6 col-md-6 form-group">
                <%= f.label :occlucion, "Occlucion" %>
                <%= f.text_field :occlusion, autofocus: true, class: 'form-control' %>
              </div>
              <div class="col-xs-12 col-sm-6 col-md-6 form-group">
                <%= f.label :periodontal_condition, "Periodontal Condition" %>
                <%= f.text_field :periodontal_condition, autofocus: true, class: 'form-control' %>
              </div>
              <div class="col-xs-12 col-sm-6 col-md-6 form-group">
                <%= f.label :oral_hygiene, "Oral Hygiene" %>
                <%= f.text_field :oral_hygiene, autofocus: true, class: 'form-control' %>
              </div>

             <div class="col-xs-12 col-sm-6 col-md-6 form-group">
                <%= f.label :denture_location, "Denture Location" %>
                <%= f.text_field :denture_location, autofocus: true, class: 'form-control' %>
              </div>
              <div class="col-xs-12 col-sm-6 col-md-6 form-group">
                <%= f.label :denture_since, "Denture Since" %>
                <%= f.date_field :denture_since, autofocus: true, class: 'form-control' %>
              </div>
              <div class="col-xs-12 col-sm-6 col-md-6form-group">
                <%= f.label :abnormalities, "abnormalities" %>
                <%= f.text_field :abnormalities, autofocus: true, class: 'form-control' %>
              </div>
              <div class="col-xs-12 col-sm-6 col-md-6 form-group">
                <%= f.label :general_condition, "General Condition" %>
                <%= f.text_field :general_condition, autofocus: true, class: 'form-control' %>
              </div>
              <div class="col-xs-12 col-sm-6 col-md-6 form-group">
                <%= f.label :nature_of_treatment, "Nature of Treatment" %>
                <%= f.text_field :nature_of_treatment, autofocus: true, class: 'form-control' %>
              </div>
              <div class="col-xs-12 col-sm-6 col-md-6 form-group">
                <%= f.label :allergies, "Allergies" %>
                <%= f.text_field :allergies, autofocus: true, class: 'form-control' %>
              </div>
              <div class="col-xs-12 col-sm-6 col-md-6 form-group">
                <%= f.label :bleeding_history, "History of Bleeding" %>
                <%= f.text_field :bleeding_history, autofocus: true, class: 'form-control' %>
              </div>
              <div class="col-xs-12 col-sm-6 col-md-6 form-group">
                <%= f.label :chronic_ailments, "Chronic Ailments" %>
                <%= f.text_field :chronic_ailments, autofocus: true, class: 'form-control' %>
              </div>
              <div class="col-xs-12 col-sm-6 col-md-6 form-group">
                <%= f.label :blood_pressure, "Blood Pressure" %>
                <%= f.text_field :blood_pressure, autofocus: true, class: 'form-control' %>
              </div>
              <div class="col-xs-12 col-sm-6 col-md-6 form-group">
                <%= f.label :drug_taken, "Drug Taken" %>
                <%= f.text_field :drug_taken, autofocus: true, class: 'form-control' %>
              </div>
              <div class="col-xs-12 col-sm-12 col-md-6 form-group">
                <%= f.submit "Save New Record", class: "btn btn-primary btn-block" %>
              </div>
            <% end %>
        </div>
    </div>
</div>

app/views/clinics/index.html.erb
<div class="row">
	<div class="col-md-4">
	<%= @clinic.clinic_name %>
	<h3>List of Appointments:</h3>
		<ul>
			<% @appointments.each do | appointment|%>
				<li><%= appointment.first_name + " " + appointment.last_name + " -- " + Date.parse(appointment.preferred_date.to_s).strftime("%B %e, %Y") + " " + DateTime.parse(appointment.preferred_date.to_s).strftime("%l:%M %p")  %> <%= link_to "Edit", edit_clinic_appointment_path(@clinic, appointment)%> | <%= link_to "Add Patient", clinic_appointment_path(@clinic, appointment) %></li>
			<%end%>
		</ul>
		
	</div>
	<div class="col-md-8">
	
		<% @clinic %>
		<% if @clinic == nil %>
			<%= link_to "Add Clinic", new_clinic_path %>
		<%end%>
	</div>
</div>

app/views/clinics/new.html.erb
<div class="row">
	<div class="mainbody-container">
		<h1>Create Clinic</h1>

		<%= form_for @clinic do |f| %>
			<%= render "shared/error_message", :target => @clinic %>
			<div class="form-group">
				<%= f.label :clinic_name, "Name of Clinic" %>
				<%= f.text_field :clinic_name, autofocus: true, class: 'form-control' %>
			</div>
			<div class="form-group">
				<%= f.label :address, "Clinic Address" %>
				<%= f.text_field :address, autofocus: true, class: 'form-control' %>
			</div>
			<div class="form-group">
				<%= f.label :city, "City" %>
				<%= f.text_field :city, autofocus: true, class: 'form-control' %>
			</div>
			<div class="form-group">
				<%= f.label :province, "Province" %>
				<%= f.text_field :province, autofocus: true, class: 'form-control' %>
			</div>
			<div class="form-group">
				<%= f.label :telephone_number, "Telephone #" %>
				<%= f.text_field :telephone_number, autofocus: true, class: 'form-control' %>
			</div>
			<div class="form-group">
				<%= f.label :mobile_number, "Mobile #" %>
				<%= f.text_field :mobile_number, autofocus: true, class: 'form-control' %>
			</div>
			<div class="form-group">
				<%= f.label :description, "Clinic description" %>
				<%= f.text_area :description, size: "20x5",autofocus: true, class: 'form-control',placeholder: "Description of your Clinic" %>
			</div>
			<div class="actions">
				<%= f.submit "Create Clinic", class: "btn btn-primary btn-block" %>
			</div>

		<% end %>
	</div>
</div>

app/views/doctors/edit.html.erb
<div class="row">
	<div class="col-md-4">
		
	</div>
	<div class="col-md-8">
		<div class="mainbody-container">
			<h1>Edit Doctor</h1>

				<%= form_for( @doctor,:url => {:action => 'update', :id => @doctor}) do |f| %>
					<%= render "shared/error_message", :target => @doctor %>
					<div class="form-group">
						<%= f.label :first_name, "First Name" %>
						<%= f.text_field :first_name, autofocus: true, class: 'form-control' %>
					</div>
					<div class="form-group">
						<%= f.label :middle_name, "Last Name" %>
						<%= f.text_field :middle_name, autofocus: true, class: 'form-control' %>
					</div>
					<div class="form-group">
						<%= f.label :last_name, "Last Name" %>
						<%= f.text_field :last_name, autofocus: true, class: 'form-control' %>
					</div>
					<div class="form-group">
						<%= f.label :birthdate, "Birthday" %>
						<%= f.text_field :birthdate, autofocus: true, class: 'form-control' %>
					</div>
					<div class="form-group">
						<%= f.label :prc_number, "PRC Number" %>
						<%= f.text_field :prc_number, autofocus: true, class: 'form-control' %>
					</div>
					<div class="form-group">
						<%= f.label :contact_num, "Mobile #" %>
						<%= f.text_field :contact_num, autofocus: true, class: 'form-control' %>
					</div>
					
					<div class="actions">
						<%= f.submit "Create Clinic", class: "btn btn-primary btn-block" %>
					</div>

				<% end %>
		</div>
	</div>
	
</div>

app/views/doctors/index.html.erb
<div class="row">
	<h2>List of Doctors</h2>
	<ul>
		<% @doctors.each do | doctor | %>
		
			<li><%= link_to doctor.first_name + " " + doctor.last_name, edit_clinic_doctor_path(@clinic, doctor) %></li>
		<%end%>
	</ul>

	<%= link_to "Add Doctor", new_clinic_doctor_path %>
</div>

app/views/doctors/new.html.erb
<div class="row">
	<div class="col-md-4">
		
	</div>
	<div class="col-md-8">
		<div class="mainbody-container">
			<h1>Add Doctor</h1>
				<%= render "shared/doctor/doctor_new_edit" %>
			
		</div>
	</div>
	
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DentalReservation</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%=render "shared/navbar" %>




<div class="container-fluid">
	<p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  <%= yield %>
</div>

</body>
</html>

app/views/patients/index.html.erb
<div class="row">
  <div class="col-md-12">
  <ul>
  	<% @records.each do | record | %>
  		<li><%= record.patient.first_name %></li>
  	 
  	<% end %>
  </ul>
  	
  </div>
</div> 

app/views/shared/_error_message.html.erb
<% if target.errors.any? %>
	<div class="error_explanation">
	  <h2><%= pluralize(target.errors.count, "error") %> prevented this record from being saved:</h2>
	  <ul>
	  <% target.errors.full_messages.each do |msg| %>
	    <li><%= msg %></li>
	  <% end %>
	  </ul>
	</div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Brand</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <% if user_signed_in? %>
      <ul class="nav navbar-nav">
      
        <li class="active"><a href="/">Home<span class="sr-only">(current)</span></a></li>
        <li><%= link_to "Set Appointment", new_clinic_appointment_path(current_user.id) %></li>
        <li><%= link_to "Doctors", clinic_doctors_path(current_user.id)%></li>
        <li><%= link_to "Patients", patients_path %></li>
        <!-- <li><a href="/">Patients</a></li>
        
        <li><a href="/">Transactions</a></li>
        <li><a href="/">Payments</a></li>
        <li><a href="/">Services</a></li> -->
        
      </ul>
      <% end %>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= "Hi, "+current_user.email %> <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="#">View Profile</a></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Sign-out", destroy_user_session_path, :method => 'delete' %></li>
            </ul>
          </li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/shared/doctor/_doctor_new_edit.html.erb
<%= form_for(@doctor, {:url => clinic_doctors_path(@clinic)}) do |f| %>
	<%= render "shared/error_message", :target => @doctor %>
	<div class="form-group">
		<%= f.label :first_name, "First Name" %>
		<%= f.text_field :first_name, autofocus: true, class: 'form-control' %>
	</div>
	<div class="form-group">
		<%= f.label :middle_name, "Last Name" %>
		<%= f.text_field :middle_name, autofocus: true, class: 'form-control' %>
	</div>
	<div class="form-group">
		<%= f.label :last_name, "Last Name" %>
		<%= f.text_field :last_name, autofocus: true, class: 'form-control' %>
	</div>
	<div class="form-group">
		<%= f.label :birthdate, "Birthday" %>
		<%= f.text_field :birthdate, autofocus: true, class: 'form-control' %>
	</div>
	<div class="form-group">
		<%= f.label :prc_number, "PRC Number" %>
		<%= f.text_field :prc_number, autofocus: true, class: 'form-control' %>
	</div>
	<div class="form-group">
		<%= f.label :contact_num, "Mobile #" %>
		<%= f.text_field :contact_num, autofocus: true, class: 'form-control' %>
	</div>
	
	<div class="actions">
		<%= f.submit "Create Clinic", class: "btn btn-primary btn-block" %>
	</div>

<% end %>